### PR TITLE
Develop 3.0

### PR DESCRIPTION
**Pull request by ThomasArts**
Make current develop-3.0 contain develop-3.0-lower changes (minus the lower in riak_pb)

### CODE REVIEW

**Comment by martincox** [comment]
Not sure if something's gone pear shaped here, this deletes riak_repl_pb.erl - is that intentional?

**Comment by martinsumner** [comment]
The .gitignore has been changed to remove all `_pb.erl` files in `src`.  Is this correct?  Is there both generated and non-generated `_pb.erl` files

**Comment by martinsumner** [comment]
@martincox this does look right (to remove `riak_repl_pb.erl`) as this is an auto-generated file.  The file is not in `develop-2.2` either.

**Comment by martincox** [comment]
I was stupidly looking at develop when I cross referenced - didn't realise it was generated. 

:+1:

**Pull request merged**
